name: Update GitHub Data
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: pip install watchy
    - name: Collect data
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WATCHY_DIR: .  # Write to current directory instead of .watchy
      run: |
        watchy stars runsascoded ryan-williams hudcostreets bikejc embankmentjc neighbor-ryan
        watchy follows runsascoded ryan-williams hudcostreets bikejc embankmentjc neighbor-ryan
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update data $(date -u +%Y-%m-%d)"
          git push
        fi
